version: '3.8'
services:
  frontend:
    build: frontend
    image: wildingka/loandefaultapptest:frontend-v1  # Same repository, different tag for frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: always
    networks:
      - app
    container_name: frontend
    
  backend:
    build: backend
    image: wildingka/loandefaultapptest:backend-v1  # Same repository, different tag for backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    restart: always
    networks:
      - app
    container_name: backend

networks:
  app:
    driver: bridge
